                                                                                                                                                                                                                                                                                        //@author:ÔķŇőᾝüĄĦᾍŉ¦ǠǕņĿ®đþĜĒ¾ĀĈĈĈÄĚĖôĢſĹòĚύýĄĦǌŎ¦ýòĊĊÆĔĔĚĐ¾ćăâĬĀʔɿŘŇ¦ĝĻņŀ®ĲņœᾡûðÿøĊÀĜĎĠĐ¸ĂĆĊâÜŋœţᾥôðĪōƺüĄīœŎîðÿøĊÀĜĎĠĐ·ĉćĊâÜŋœţᾥôðĦŀƸüŌþĺňƀĳòąøÀĖĖĚĖ¶ĂĆĎĊ
package com.mycompany.doanbmtt;

import java.security.PublicKey;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**@author
 * Nhóm ChillGroup
 * Nguyễn Hải Đăng - 2280600668
 * Bùi Bảo Hân - 2280600871
 * Trương Minh Nhiều - 2280602242
 * Nguyễn Xuân Minh - 2280601952
 * Nguyễn Thành Phúc - 2280602462
 */
public class frmKhoiPhucMK extends javax.swing.JFrame {
    private static final String url = "jdbc:sqlserver://FAROLPC\\SQLEXPRESS:1433;databaseName=ENGCHECK;encrypt=true;trustServerCertificate=true;";
    private static final String username = "sa";
    private static final String password = "123456789";
    /**
     * Creates new form frmKhoiPhucMK
     */
    public frmKhoiPhucMK() {
        this.setUndecorated(true);
        initComponents();
        lbMK.setVisible(false);
        lbXTMK.setVisible(false);
        txtPass.setVisible(false);
        txtPassCheck.setVisible(false);
        btnXacNhan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOTP = new javax.swing.JTextField();
        btnGuiOTP = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        lbXTMK = new javax.swing.JLabel();
        lbCheck = new javax.swing.JLabel();
        txtPassCheck = new javax.swing.JPasswordField();
        lbMK = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnXacThuc = new javax.swing.JButton();
        btnBack = new javax.swing.JLabel();
        lbThongBao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IconVietnam = new javax.swing.JLabel();
        HinhNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("Đổi mật khẩu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 480, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 340, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setText("Nhập OTP ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(txtOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 190, 40));

        btnGuiOTP.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnGuiOTP.setText("Gửi OTP");
        btnGuiOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiOTPActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuiOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 120, 40));

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 140, 40));

        lbXTMK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbXTMK.setText("Xác thực mật khẩu");
        getContentPane().add(lbXTMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));
        getContentPane().add(lbCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 40, 30));
        getContentPane().add(txtPassCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 260, 40));

        lbMK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbMK.setText("Mật khẩu mới");
        getContentPane().add(lbMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 260, 40));

        btnXacThuc.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btnXacThuc.setText("Xác thực");
        btnXacThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacThucActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 140, 40));

        btnBack.setIcon(new javax.swing.ImageIcon("F:\\1Hutech\\BaoMat\\DoAn\\DoAnBMTT\\src\\main\\java\\com\\mycompany\\doanbmtt\\HinhNen\\btnback.png")); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        lbThongBao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(lbThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 900, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Made by ChillGroup");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));

        IconVietnam.setIcon(new javax.swing.ImageIcon("F:\\1Hutech\\BaoMat\\DoAn\\DoAnBMTT\\src\\main\\java\\com\\mycompany\\doanbmtt\\HinhNen\\iconVietNam.png")); // NOI18N
        getContentPane().add(IconVietnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        HinhNen.setIcon(new javax.swing.ImageIcon("F:\\1Hutech\\BaoMat\\DoAn\\DoAnBMTT\\src\\main\\java\\com\\mycompany\\doanbmtt\\HinhNen\\HinhNenKhoiPhuc.jpg")); // NOI18N
        getContentPane().add(HinhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiOTPActionPerformed
        String email = txtEmail.getText(); 
    if (email.isEmpty() || !email.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
        lbThongBao.setText("Email không hợp lệ! Vui lòng nhập email đúng định dạng (ví dụ: example@gmail.com)");
        return;
    }

    if (!isEmailExists(email)) {
        lbThongBao.setText("Tài khoản này không tồn tại. Vui lòng đăng ký.");
        return;
    }

    OTPGmail.sendOTP(email); 
    lbThongBao.setText("OTP đã được gửi đến email của bạn.");
    }//GEN-LAST:event_btnGuiOTPActionPerformed
    private boolean isEmailExists(String email) {
    String query = "SELECT COUNT(*) FROM NguoiDung WHERE email = ?";
    try (Connection conn = DriverManager.getConnection(url, username, password);
         PreparedStatement stmt = conn.prepareStatement(query)) {
        stmt.setString(1, email);
        ResultSet rs = stmt.executeQuery();
        if (rs.next() && rs.getInt(1) > 0) {
            return true;         }
    } catch (SQLException e) {
    }
    return false; }
    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String email = txtEmail.getText();     String newPassword = new String(txtPass.getPassword());     String confirmPassword = new String(txtPassCheck.getPassword()); 
        if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
        lbThongBao.setText("Vui lòng nhập đầy đủ mật khẩu và xác nhận mật khẩu!");
        return;
    }

    if (!newPassword.equals(confirmPassword)) {
        lbThongBao.setText("Mật khẩu xác nhận không khớp!");
        return;
    }

    if (!newPassword.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=-]).{8,20}$")) {
        lbThongBao.setText("Mật khẩu phải từ 8-20 ký tự, gồm chữ hoa, chữ thường, số và ký tự đặc biệt!");
        return;
    }

    try {
                String aesKey = EncryptionHelper.generateAESKey();         String encryptedPassword = EncryptionHelper.encryptAES(newPassword, aesKey);         PublicKey publicKey = EncryptionHelper.loadPublicKey("src/resources/publicKey.pem");         String encryptedAESKey = EncryptionHelper.encryptRSA(aesKey, publicKey); 
                updatePassword(email, encryptedPassword, encryptedAESKey);
        lbThongBao.setText("Mật khẩu đã được cập nhật thành công!");
        resetForm();
    } catch (Exception e) {
        lbThongBao.setText("Lỗi khi cập nhật mật khẩu: " + e.getMessage());
    }
    }//GEN-LAST:event_btnXacNhanActionPerformed
    private void updatePassword(String email, String encryptedPassword, String encryptedAESKey) {
    String query = "UPDATE NguoiDung SET mat_khau_ma_hoa = ?, khoa_aes_ma_hoa = ? WHERE email = ?";
    try (Connection conn = DriverManager.getConnection(url, username, password);
         PreparedStatement stmt = conn.prepareStatement(query)) {
        stmt.setString(1, encryptedPassword);
        stmt.setString(2, encryptedAESKey);
        stmt.setString(3, email);
        stmt.executeUpdate();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật mật khẩu: " + e.getMessage());
    }
    }

        private void resetForm() {
        txtEmail.setText("");
        txtOTP.setText("");
        txtPass.setText("");
        txtPassCheck.setText("");
        txtEmail.setEditable(true);
        txtOTP.setEditable(true);
        lbMK.setVisible(false);
        lbXTMK.setVisible(false);
        txtPass.setVisible(false);
        txtPassCheck.setVisible(false);
        btnXacNhan.setVisible(false);
    }
    private void btnXacThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacThucActionPerformed
        String userInputOtp = txtOTP.getText(); 
        String generatedOtp = OTPGmail.getGeneratedOTP(); 

    if (userInputOtp.isEmpty()) {
        lbThongBao.setText("Vui lòng nhập OTP để kiểm tra!");
        return;
    }

    if (userInputOtp.equals(generatedOtp)) {
        lbThongBao.setText("Mã OTP hợp lệ! Bạn có thể tiếp tục.");
        txtOTP.setEditable(false); 
        txtEmail.setEditable(false);
        lbMK.setVisible(true);
        lbXTMK.setVisible(true);
        txtPass.setVisible(true);
        txtPassCheck.setVisible(true);
        btnXacNhan.setVisible(true);
    } else {
        lbThongBao.setText("Mã OTP không hợp lệ! Vui lòng thử lại.");
    }
    }//GEN-LAST:event_btnXacThucActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http:         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmKhoiPhucMK().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HinhNen;
    private javax.swing.JLabel IconVietnam;
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnGuiOTP;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXacThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbCheck;
    private javax.swing.JLabel lbMK;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbXTMK;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassCheck;
    // End of variables declaration//GEN-END:variables
}
                                                                                                                                                                                                                                                                                        //@author:ÔķŇőᾝüĄĦᾍŉ¦ǠǕņĿ®đþĜĒ¾ĀĈĈĈÄĚĖôĢſĹòĚύýĄĦǌŎ¦ýòĊĊÆĔĔĚĐ¾ćăâĬĀʔɿŘŇ¦ĝĻņŀ®ĲņœᾡûðÿøĊÀĜĎĠĐ¸ĂĆĊâÜŋœţᾥôðĪōƺüĄīœŎîðÿøĊÀĜĎĠĐ·ĉćĊâÜŋœţᾥôðĦŀƸüŌþĺňƀĳòąøÀĖĖĚĖ¶ĂĆĎĊ